name: test
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - run: |
        cargo test
        cargo test --manifest-path=wfc/Cargo.toml --features=parallel
        cargo test --manifest-path=wfc-image/Cargo.toml --features=parallel
