[package]
name = "wfc"
description = "Generate images using Wave Function Collapse"
version = "0.9.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/wfc.git"
repository = "https://github.com/stevebob/wfc.git"
documentation = "https://docs.rs/wfc"
edition = "2018"

[dependencies]
rand = "0.7"
hashbrown = "0.7"
coord_2d = "0.2"
grid_2d = "0.14"
direction = "0.17"

